### ISSUE TITLE
jstat -class option man doc typo

### ISSUE THREAD

**Issue by Bambooin** [AdoptOpenJDK/openjdk-jdk#3]
Due to it's automatically generated by Pandoc 2.3.1, pull request to this doc maybe is unaccepted.

Don't have openjdk account to report issue to openjdk project jira.

https://github.com/openjdk/jdk/blame/d34f561de002510c818c73cd5871caf2222ca0a7/src/jdk.jcmd/share/man/jstat.1#L227

Bytes: Number of KB loaded. --> Bytes: Number of KB unloaded.

**Comment by karianna** [comment]
@Bambooin - this needs to be reported upstream at the serviceability-dev mailing list at openjdk.java.net :-).

**Comment by Bambooin** [comment]
Thanks for your help, the bug is already filed by David.

https://bugs.openjdk.java.net/browse/JDK-8249450

**Comment by karianna** [comment]
@Bambooin Thanks for reporting it and following through!
